[HMA-3244] Uplift getPreferences response to match future structure
hmrc/customer-profile pull request #91
Opened 2020-10-07 11:28 UTC by mrolfe88

2020-10-07 11:42 UTC, mrolfe88 commented
test this please

2020-10-07 11:53 UTC, georgeherby requested changes

2020-10-07 11:53 UTC, georgeherby commented on app/uk/gov/hmrc/customerprofile/connector/preferencesFrontendConnector.scala
> +
?????

2020-10-08 09:23 UTC, georgeherby approved these changes

2020-10-08 09:29 UTC, mrolfe88 commented
test this please

2020-10-08 09:43 UTC, mrolfe88 commented
test this please

2020-10-08 09:47 UTC, merged